repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
    - id: check-added-large-files
      args: ['--maxkb=1024']
    -id: detect-aws-credentials
