name: myna
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1.3
  - numpy=1.19.1
  - pandas=1.1.1
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.6.0
  - pytorch-lightning=0.9.0
  - torchaudio=0.6.0
  - torchvision=0.7.0
  - pip:
    - pre-commit==1.21.0
    - num2words==0.5.10
    - hydra-core==1.0.3
    - editdistance==0.5.3