paths:
  csv_train: "path to train.csv"
  save_checkpoints: "path folder for saving checkpoints"
  log_path: "path folder for saving tensorboard logs"

train_config:
  lr: 1e-3
  n_mels: 128
  max_epoches: 30
  batch_size: 16

hydra:
  output_subdir: null
  run:
    dir: ./

defaults:
  - hydra/job_logging: stdout